//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDiscipline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinary
    {
        public int Id { get; set; }
        public string Regno { get; set; }
        public decimal level { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
