//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDiscipline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Disciplinaries = new HashSet<Disciplinary>();
        }
    
        public string Regno { get; set; }
        public string FullName { get; set; }
        public string School { get; set; }
        public string SchoolCode { get; set; }
        public string LearningMode { get; set; }
    
        public virtual ICollection<Disciplinary> Disciplinaries { get; set; }
    }
}
